services:
  - type: web
    name: nguyenphamdieuhien.online
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r agent_finance/requirements.txt
    startCommand: uvicorn agent_finance.back.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CRAWLING_BOT_DB
        sync: false
      - key: GLOBAL_INDICATOR_DB
        sync: false
      - key: ARGUS_FINTEL_DB
        sync: false
      - key: DB_SCHEMA
        value: public
      - key: CORS_ALLOW_ORIGINS
        value: https://nguyenphamdieuhien.online,https://www.nguyenphamdieuhien.online,https://hiienng.github.io,http://localhost:3000,http://127.0.0.1:5500
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_API_AUDIENCE
        value: https://api.nguyenphamdieuhien.online
      - key: AUTH0_CALLBACK_URL
        value: https://api.nguyenphamdieuhien.online/callback
      - key: LOGOUT_URL
        value: https://nguyenphamdieuhien.online/vietdataverse/index.html
