services:
  - type: web
    name: vietdataverse-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CRAWLING_BOT_DB
        sync: false
      - key: GLOBAL_INDICATOR_DB
        sync: false
      - key: ARGUS_FINTEL_DB
        sync: false
      - key: DB_SCHEMA
        value: public
      - key: CORS_ALLOW_ORIGINS
        value: https://vietdataverse.online,https://www.vietdataverse.online,https://findatasolution.github.io,http://localhost:3000,http://127.0.0.1:5500
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_API_AUDIENCE
        value: https://api.vietdataverse.online
      - key: AUTH0_CALLBACK_URL
        value: https://api.vietdataverse.online/callback
      - key: LOGOUT_URL
        value: https://vietdataverse.online/index.html
